# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-23 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170323_0730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='paretn',
            new_name='parent',
        ),
    ]
