# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-05 06:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 6, 8, 10, 248623, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
